Document: fonts-roboto-slab
Title: Debian fonts-roboto-slab Manual
Author: <insert document author here>
Abstract: This manual describes what fonts-roboto-slab is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fonts-roboto-slab/fonts-roboto-slab.sgml.gz

Format: postscript
Files: /usr/share/doc/fonts-roboto-slab/fonts-roboto-slab.ps.gz

Format: text
Files: /usr/share/doc/fonts-roboto-slab/fonts-roboto-slab.text.gz

Format: HTML
Index: /usr/share/doc/fonts-roboto-slab/html/index.html
Files: /usr/share/doc/fonts-roboto-slab/html/*.html
